// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1:number,arg2:number,arg3:number,arg4:Array<number>,arg5:string):Promise<Record<string, any>>;

export function EncryptFile(arg1:number,arg2:number,arg3:number,arg4:Array<number>,arg5:string):Promise<Record<string, any>>;
